=== AlexRogalskiy/java-frameworks/jaxb/src/test/resources/lodging-test.xsd
<?xml version="1.0" encoding="UTF-8"?> 
<schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
	<element name="lodgingDto">
		
       <complexType>
			<sequence>
				<element name="id" type="xs:long" />
				<element name="address" type="xs:string" />
				<element name="city" type="xs:string" />
				<element name="county" type="xs:string" />
				<element name="state" type="xs:string" />
				<element name="country" type="xs:string" />
				<element name="phoneNumber" type="xs:string" />
				<element name="roomDto">
					<complexType>
						<sequence>
							<element name="id" type="xs:long" />
							<element name="type" type="xs:string" />
							<element name="extras" type="xs:string" />
						</sequence>
					</complexType>
				</element>
			</sequence>
		</complexType>>
    </element>
<schema></schema>

=== AlexRogalskiy/java-frameworks/jaxb/src/test/resources/lodgings-test.xml
<?xml version="1.0" standalone="no"?>
<lodgingDto xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" 
                  xsi:noNamespaceSchemaLocation="lodging-test.xsd">
	<id>1</id>
	<address>Calle torreciudad</address>
	<city>Barbastro</city>
	<county>Huesca</county>
	<state>Arag√≥n</state>
	<country>Spain</country>
	<phoneNumber>+34974315856</phoneNumber>
	<roomDto>
		<id>1</id>
		<type>Individual</type>
		<extras>Personal Sauna</extras>
	</roomDto>
</lodgingDto>
